# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vegard.proto import entity_pb2 as vegard_dot_proto_dot_entity__pb2
from vegard.proto import transport_pb2 as vegard_dot_proto_dot_transport__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vegard/proto/transport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeshServiceStub(object):
    """MeshService - gRPC for drone↔node communication
    Compatible with Anduril Lattice mesh patterns
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEntities = channel.stream_stream(
                '/vegard.api.v1.MeshService/StreamEntities',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                _registered_method=True)
        self.PublishEntity = channel.unary_unary(
                '/vegard.api.v1.MeshService/PublishEntity',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.PublishAck.FromString,
                _registered_method=True)
        self.SyncEntities = channel.unary_unary(
                '/vegard.api.v1.MeshService/SyncEntities',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.SyncAck.FromString,
                _registered_method=True)
        self.QueryEntities = channel.unary_unary(
                '/vegard.api.v1.MeshService/QueryEntities',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_entity__pb2.EntityHistory.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/vegard.api.v1.MeshService/Heartbeat',
                request_serializer=vegard_dot_proto_dot_transport__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class MeshServiceServicer(object):
    """MeshService - gRPC for drone↔node communication
    Compatible with Anduril Lattice mesh patterns
    """

    def StreamEntities(self, request_iterator, context):
        """Bidirectional streaming for real-time entity state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEntity(self, request, context):
        """Unary updates for low-bandwidth scenarios
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncEntities(self, request, context):
        """Batch entity sync
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryEntities(self, request, context):
        """Entity query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat for liveness
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEntities': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEntities,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            ),
            'PublishEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEntity,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.PublishAck.SerializeToString,
            ),
            'SyncEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncEntities,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.SyncAck.SerializeToString,
            ),
            'QueryEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryEntities,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_entity__pb2.EntityHistory.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.HeartbeatRequest.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vegard.api.v1.MeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vegard.api.v1.MeshService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshService(object):
    """MeshService - gRPC for drone↔node communication
    Compatible with Anduril Lattice mesh patterns
    """

    @staticmethod
    def StreamEntities(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vegard.api.v1.MeshService/StreamEntities',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.MeshService/PublishEntity',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.PublishAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.MeshService/SyncEntities',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.SyncAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.MeshService/QueryEntities',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_entity__pb2.EntityHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.MeshService/Heartbeat',
            vegard_dot_proto_dot_transport__pb2.HeartbeatRequest.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TaskServiceStub(object):
    """TaskService - Auction and task management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishTask = channel.unary_unary(
                '/vegard.api.v1.TaskService/PublishTask',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.TaskPublished.FromString,
                _registered_method=True)
        self.Bid = channel.unary_unary(
                '/vegard.api.v1.TaskService/Bid',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.BidAck.FromString,
                _registered_method=True)
        self.AcceptTask = channel.unary_unary(
                '/vegard.api.v1.TaskService/AcceptTask',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.TaskAssigned.FromString,
                _registered_method=True)
        self.StreamProgress = channel.stream_stream(
                '/vegard.api.v1.TaskService/StreamProgress',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/vegard.api.v1.TaskService/CompleteTask',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.CompletionAck.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/vegard.api.v1.TaskService/CancelTask',
                request_serializer=vegard_dot_proto_dot_transport__pb2.CancelRequest.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.CancelResponse.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """TaskService - Auction and task management
    """

    def PublishTask(self, request, context):
        """Publish a new task for bidding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Bid(self, request, context):
        """Submit a bid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptTask(self, request, context):
        """Accept/assign a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProgress(self, request_iterator, context):
        """Stream progress updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Report task completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Cancel a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTask,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.TaskPublished.SerializeToString,
            ),
            'Bid': grpc.unary_unary_rpc_method_handler(
                    servicer.Bid,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.BidAck.SerializeToString,
            ),
            'AcceptTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptTask,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.TaskAssigned.SerializeToString,
            ),
            'StreamProgress': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamProgress,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.CompletionAck.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.CancelRequest.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vegard.api.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vegard.api.v1.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """TaskService - Auction and task management
    """

    @staticmethod
    def PublishTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.TaskService/PublishTask',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.TaskPublished.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Bid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.TaskService/Bid',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.BidAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.TaskService/AcceptTask',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.TaskAssigned.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamProgress(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vegard.api.v1.TaskService/StreamProgress',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.TaskService/CompleteTask',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.CompletionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.TaskService/CancelTask',
            vegard_dot_proto_dot_transport__pb2.CancelRequest.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DriftServiceStub(object):
    """DriftService - Cross-node drift monitoring
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamDrift = channel.stream_stream(
                '/vegard.api.v1.DriftService/StreamDrift',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                _registered_method=True)
        self.QueryDrift = channel.unary_unary(
                '/vegard.api.v1.DriftService/QueryDrift',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                _registered_method=True)
        self.SubscribeAlerts = channel.unary_stream(
                '/vegard.api.v1.DriftService/SubscribeAlerts',
                request_serializer=vegard_dot_proto_dot_transport__pb2.AlertSubscription.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                _registered_method=True)
        self.RequestRecalibration = channel.unary_unary(
                '/vegard.api.v1.DriftService/RequestRecalibration',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                _registered_method=True)


class DriftServiceServicer(object):
    """DriftService - Cross-node drift monitoring
    """

    def StreamDrift(self, request_iterator, context):
        """Stream drift signals from nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryDrift(self, request, context):
        """Query drift correlations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeAlerts(self, request, context):
        """Subscribe to drift alerts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRecalibration(self, request, context):
        """Request model recalibration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamDrift': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDrift,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            ),
            'QueryDrift': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryDrift,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            ),
            'SubscribeAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeAlerts,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.AlertSubscription.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            ),
            'RequestRecalibration': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRecalibration,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vegard.api.v1.DriftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vegard.api.v1.DriftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriftService(object):
    """DriftService - Cross-node drift monitoring
    """

    @staticmethod
    def StreamDrift(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vegard.api.v1.DriftService/StreamDrift',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryDrift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.DriftService/QueryDrift',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vegard.api.v1.DriftService/SubscribeAlerts',
            vegard_dot_proto_dot_transport__pb2.AlertSubscription.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRecalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.DriftService/RequestRecalibration',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AIPBridgeServiceStub(object):
    """AIPBridgeService - REST fallback for AIP integration
    These messages map to REST API at /api/vegard/ingest
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestSoil = channel.unary_unary(
                '/vegard.api.v1.AIPBridgeService/IngestSoil',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.IngestAck.FromString,
                _registered_method=True)
        self.IngestBatch = channel.unary_unary(
                '/vegard.api.v1.AIPBridgeService/IngestBatch',
                request_serializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.BatchIngestAck.FromString,
                _registered_method=True)
        self.QueryFieldStatus = channel.unary_unary(
                '/vegard.api.v1.AIPBridgeService/QueryFieldStatus',
                request_serializer=vegard_dot_proto_dot_transport__pb2.FieldStatusRequest.SerializeToString,
                response_deserializer=vegard_dot_proto_dot_transport__pb2.FieldStatusResponse.FromString,
                _registered_method=True)


class AIPBridgeServiceServicer(object):
    """AIPBridgeService - REST fallback for AIP integration
    These messages map to REST API at /api/vegard/ingest
    """

    def IngestSoil(self, request, context):
        """Ingest soil predictions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestBatch(self, request, context):
        """Batch ingest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryFieldStatus(self, request, context):
        """Query field status from AIP perspective
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIPBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestSoil': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestSoil,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.IngestAck.SerializeToString,
            ),
            'IngestBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestBatch,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.BytesMessage.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.BatchIngestAck.SerializeToString,
            ),
            'QueryFieldStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryFieldStatus,
                    request_deserializer=vegard_dot_proto_dot_transport__pb2.FieldStatusRequest.FromString,
                    response_serializer=vegard_dot_proto_dot_transport__pb2.FieldStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vegard.api.v1.AIPBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vegard.api.v1.AIPBridgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIPBridgeService(object):
    """AIPBridgeService - REST fallback for AIP integration
    These messages map to REST API at /api/vegard/ingest
    """

    @staticmethod
    def IngestSoil(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.AIPBridgeService/IngestSoil',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.AIPBridgeService/IngestBatch',
            vegard_dot_proto_dot_transport__pb2.BytesMessage.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.BatchIngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryFieldStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vegard.api.v1.AIPBridgeService/QueryFieldStatus',
            vegard_dot_proto_dot_transport__pb2.FieldStatusRequest.SerializeToString,
            vegard_dot_proto_dot_transport__pb2.FieldStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
