# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: syndar/proto/entity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'syndar/proto/entity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from syndar.proto import common_pb2 as syndar_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19syndar/proto/entity.proto\x12\rsyndar.api.v1\x1a\x19syndar/proto/common.proto\"\x96\x02\n\x0b\x45ntityState\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.syndar.api.v1.EntityType\x12)\n\x08position\x18\x03 \x01(\x0b\x32\x17.syndar.api.v1.Position\x12\x11\n\tsoil_data\x18\x04 \x01(\x0c\x12\x13\n\x0b\x64rift_score\x18\x05 \x01(\x02\x12\x12\n\ndrift_flag\x18\x06 \x01(\x08\x12\x13\n\x0b\x62\x61ttery_pct\x18\x07 \x01(\x02\x12\x0f\n\x07task_id\x18\x08 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\t \x01(\x03\x12\x11\n\tsignature\x18\n \x01(\x0c\x12\x15\n\rmodel_version\x18\x0b \x01(\t\"y\n\x0b\x45ntityEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12*\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x1a.syndar.api.v1.EntityState\x12,\n\nevent_type\x18\x03 \x01(\x0e\x32\x18.syndar.api.v1.EventType\"Q\n\x0b\x45ntityBatch\x12,\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x1a.syndar.api.v1.EntityState\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\"b\n\x0b\x45ntityQuery\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x15\n\rstart_time_ms\x18\x02 \x01(\x03\x12\x13\n\x0b\x65nd_time_ms\x18\x03 \x01(\x03\x12\x14\n\x0cinclude_soil\x18\x04 \x01(\x08\"N\n\rEntityHistory\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12*\n\x06states\x18\x02 \x03(\x0b\x32\x1a.syndar.api.v1.EntityState*\x86\x01\n\nEntityType\x12\x1b\n\x17\x45NTITY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x45NTITY_TYPE_DRONE\x10\x01\x12\x17\n\x13\x45NTITY_TYPE_SCANNER\x10\x02\x12\x14\n\x10\x45NTITY_TYPE_BASE\x10\x03\x12\x15\n\x11\x45NTITY_TYPE_RELAY\x10\x04*\x92\x01\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x45VENT_TYPE_UPDATE\x10\x01\x12\x18\n\x14\x45VENT_TYPE_HEARTBEAT\x10\x02\x12\x1a\n\x16\x45VENT_TYPE_DRIFT_ALERT\x10\x03\x12\x1c\n\x18\x45VENT_TYPE_TASK_COMPLETE\x10\x04\x42\x32Z0github.com/EnotriumSyndicate/Syndar/syndar/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'syndar.proto.entity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/EnotriumSyndicate/Syndar/syndar/proto'
  _globals['_ENTITYTYPE']._serialized_start=739
  _globals['_ENTITYTYPE']._serialized_end=873
  _globals['_EVENTTYPE']._serialized_start=876
  _globals['_EVENTTYPE']._serialized_end=1022
  _globals['_ENTITYSTATE']._serialized_start=72
  _globals['_ENTITYSTATE']._serialized_end=350
  _globals['_ENTITYEVENT']._serialized_start=352
  _globals['_ENTITYEVENT']._serialized_end=473
  _globals['_ENTITYBATCH']._serialized_start=475
  _globals['_ENTITYBATCH']._serialized_end=556
  _globals['_ENTITYQUERY']._serialized_start=558
  _globals['_ENTITYQUERY']._serialized_end=656
  _globals['_ENTITYHISTORY']._serialized_start=658
  _globals['_ENTITYHISTORY']._serialized_end=736
# @@protoc_insertion_point(module_scope)
